using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using EFConvention;
using WebTest.Models;

namespace WebTest.Decorations
{
    public class ConventionConfiguration : IEFConventionConfigurator
    {
        public void Configure(IAutoContextFactoryConfiguration configuration)
        {
            configuration.AutoGeneratedMigrationsEnabled = true;
            configuration.AutoMigrateGeneratedMigrationsEnabled = true;
            configuration.MigrationsDirectory =
                @"C:\Users\Nero\Documents\visual studio 2013\Projects\EFAutomation\WebTest\Migrations\";
        }
    }
}