
namespace EFMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EFAutomation.MigrationDesignerGenerator", "1.0")]
    public sealed partial class First : IMigrationMetadata
    {
        //private readonly ResourceManager Resources = new ResourceManager(typeof(First));
        
        string IMigrationMetadata.Id
        {
            get { return "201401312057302_AutoGeneratedMigration140131085729"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1XyW7bMBC9F+g/CDy1h5heLm0gJ0jtuAhax0GU5E5LY4coRaoiFdjf1kM/qb/QoXZLXuIkKHoTyZk36+NQf379ds9XoXCeINZcySHpdbrEAemrgMvlkCRmcfKJnJ+9f+deBuHKeSjkBlYONaUekkdjolNKtf8IIdOdkPux0mphOr4KKQsU7Xe7n2mvRwEhCGI5jnubSMNDSBe4HCnpQ2QSJqYqAKHzfTzxUlTnmoWgI+bDkFxOpnwZM4N+aOJcCM7QBw/EgjhMSmXSk9N7DZ6JlVx6EW4wcbeOAOUWTGjIPT+txJ8bRLdvg6CV4ouSQMrwMMBLTIRZW/fSIIfkysCGBMp8g/XGBm7dxCqC2KxvYVHoBcShm3q0qViq1XSsafySZtAnznUiBJsLKDNVS6lnVAxfQQImH4IbZgzE0mJAGkLLesPWKAarVxgc4+IOW2CLzf04qMgKECwx9ilxpmz1HeTSPA4JfhJnwlcQFDs56r3k2NaoZOLkWUb6/8TK4I2tuLTqqHafIdEM41jCoii4hpVp9Fsm64GptSRyrQLOCNdJW3Wr9dJOxWSaUbmgPN3BeXfKoggTUbsD8h3Hyy6A0Yl3PO3CDIP6egv7Sm9LS9jqbAmNU5uuACY81sZWbs5sKUZBuEVsb1YLK/XkNvld5bqQtt+ZRv0G7LSvi3rOJhhGiPxMI4LSg223TK7o+UyweMs9MVIiCeWuu2afdsn8OkS5+XycjPl1kGznOIR+G6J/LMagjTHYhuHSRh2aZaatOjdu8GbT7ONaU6S0XnKuwS037/PDQ7fV+JkIcTA5TzywTe+tNfZUxwp0vJ9iJDjGWwlMmeQL0OZO/QCcGv1ur9+Y3i+YpFTrQPyP45Tb0A8OzCMnX2OCBrgwr52g8onF/iOLP4Rs9bGOdPSUfDXS4AVIx0675vV9eO7tHHsZA7AMc4WOZw7mg/KFE7HNRpfWH8ruGDRfVhD22SzBt3OgAi1kruRCFUnGiOoeFSKNGkzBMOwpdhEbvmC+wWMftE4fJQ9MJHbyhHMIruQsMVFiLrSGcC42Hn4u3W8/HfubPruzKJ1kbxECusktLWbyS8JFUPo9adNiF4TtkZyz6BU+yhBuuS6RrpV8JlCevjFEIC3j7yCMBILpmfTYE+z27XAONzPmjjnD50Coc4xK3/63UfvjdvYX0mC0XOoNAAA="; }
		}
	}
}