namespace EFMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EFAutomation.MigrationDesignerGenerator", "1.0")]
    public sealed partial class AutoGeneratedMigration140131093410 : IMigrationMetadata
    {
        //private readonly ResourceManager Resources = new ResourceManager(typeof(First));
        
        string IMigrationMetadata.Id
        {
            get { return "201401312134107_AutoGeneratedMigration140131093410"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1Y227TQBB9R+IfrH2CB7Jp0lZQOaCSNqiCtAi3fd/Yk3TFetd411XybTzwSfwCs77HzqVuq4q3eD1z5uKZ4+P8/f3H/bQMhXMPseZKjshBr08ckL4KuFyMSGLm796TTx9fv3LPg3Dp3BZ2Q2uHnlKPyJ0x0Qml2r+DkOleyP1YaTU3PV+FlAWKDvr9D/TggAJCEMRyHPdHIg0PIb3Ay7GSPkQmYWKqAhA6P8c7XorqXLIQdMR8GJHzyZQvYmYwD02cU8EZ5uCBmBOHSalMeufkRoNnYiUXXoQHTFyvIkC7ORMa8sxPKvOHFtEf2CJo5fioJpCyPCzwHBthVja9tMgRuTCwZoE2X2G1doBH32MVQWxWP2Be+AXEoet+tOlYutV8bGj8Jc1wQJzLRAg2E1B2qtZSz6gYvoAEbD4E35kxEEuLAWkJreiNWOMYrF8R8AwvrnEENsTcjYOOrADBR4xzSpwpW34DuTB3I4I/iTPhSwiKkxz1RnIca3QycfKgIIMXiTJ8kSiHLxLlaN807Yc47gLh0mp72juFpGIYx3EtBhCvYWkau5XZemBq64e8UgFn5NJL13Jj9DJOxVo0o62C3ugWfnOnLIrwcdT4Lj9xvIzsxu+87hQTZhjU1xuYpsy2jIRrzRbQuGvbFcCEx9rYxzJjtvfjINxgtrOrRZR6c5tcVvW6sLa/M4862/fa1Fjv2QTLCJGL0oqgzGATo+aOns8Eizdw4liJJJTbeHWXd8lydYjy8OE4GcvVQbKTbgiDNsSgK8awjTHsinHYxjjsinHUxjjqinHcxjjehOHSxkw1R5a2Zrbx5m0uwC7eaJqU0Uv+aPCEm+/sfrHUWuLMhDjYnHse2AX2Vhr3o2cNet4vMRYc660MpkzyOWhzrX4Cvu0H/YNBQ3U9QgFRrQPxP8ogbkvfK3Q6vtcayifAC/NU5SPvWezfsfhNyJZv60id1c2TkYbPhnT4bEhHaw/0KTpkP0BXFdJ8re7XI1vlSLbNOFIzhflmGeYC5pFKpc0sLq1/rLlnoPmigrCfbhJ8+36uQAubCzlXRW+xonpGhUmj9VMwDPeDncaGz5lv8LYPWqeS9ZaJxCqCcAbBhbxKTJSYU60hnIm1jw+X7o6fyrH1nN2rKFUYz1ECpsntil/JzwkXQZn3ZMPkbIGwM5LzD2aFkh3hFqsS6VLJBwLl7TuDCKRlr2sII4Fg+kp67B6257a/h+sdc884Q5kW6hyj8rf/HVD758HHf/SDGhVuEAAA"; }
		}
	}
}