namespace EFMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EFAutomation.MigrationDesignerGenerator", "1.0")]
    public sealed partial class AutoGeneratedMigration140201094440 : IMigrationMetadata
    {
        //private readonly ResourceManager Resources = new ResourceManager(typeof(First));
        
        string IMigrationMetadata.Id
        {
            get { return "201402010944406_AutoGeneratedMigration140201094440"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1Y227TQBB9R+IfrH2Ch2bTRK2gcoratEEVpEU48L6xJ+mK9a7xrqvk23jgk/gFZn2PnUvdVog3ez1z5uKZ45P8+fXb/bAKhfMAseZKjshxr08ckL4KuFyOSGIWR+/Ih/PXr9zrIFw53wu7obVDT6lH5N6Y6IxS7d9DyHQv5H6stFqYnq9CygJFB/3+e3p8TAEhCGI5jvs1kYaHkN7g7VhJHyKTMDFVAQidn+MTL0V1blkIOmI+jMj1ZMqXMTOYhybOheAMc/BALIjDpFQmfXL2TYNnYiWXXoQHTMzWEaDdggkNeeZnlflji+gPbBG0cnxSE0hZHhZ4jY0wa5teWuSI3BjYsECbT7DeOMCjL7GKIDbrr7Ao/ALi0E0/2nQs3Wo+NjReSTMcEOc2EYLNBZSdqrXUMyqGjyABmw/BF2YMxNJiQFpCK3oj1jgG61cEvMKbGY7Alpj7cdCRFSD4inFOiTNlq88gl+Z+RPCSOBO+gqA4yVG/SY5jjU4mTh4VZPBPogz/SZSTQ+/5MMTp8yBmoM2lUqJAsdfA5AEcl1b70d4apA3DOA5kMWJ4DyvT2J7M1gNTWzBkjgo4o49eunhbo5dxKl6iGTEVBEZ3MJg7ZVGEr7XGaPmJ42V0Nj7yupNImGFQX2/hkjLbMhIuLltC46ltVwATHmtjX++c2d6Pg3CL2d6uFlHqzW2yVdXrwtpeZx51Pu+1ya/eswmWESLbpBVBmcE2zswdPZ8JFm9hvbESSSh3Mec+75LH6hDl4eNxMh6rg2Qn3RAGbYhBV4xhG2PYFeOkjXHSFeO0jXHaBaOimDpMddpGcmljspqDS1uT2/jCNtdgH3s0TcroJYs02MLNN/ewKGqtcmZCHGzRAw/sGntrjVvSswY976cYC471VgZTJvkCWzVTPwC/6oP+8aChrp6gdKjWgfgf5Q63pR8UNB0/cQ2FE+CNea7CkQ8s9u9Z/CZkq7d1pM4q5tlIwxdDOtl4Dc/RIk8BaCqROT+E0VWFND+rh/XITjmS7TEO01xhvlmGuYB5olJpc4pL6z/H3CvQfFlB2B9nEnz7fa5AC5sbuVBFe7GiekaFSaP7UzAMN4NdxIYvmG/wsQ9ap9L3OxOJVQThHIIbeZeYKDEXWkM4Fxs/L1y6P34qxzZzdu+iVGG8RAmYJrfLfScvEy6CMu/JlsnZAWFnJGcezAqlP8It1yXSrZKPBMrbdwURSMtbMwgjgWD6TnrsAXbndriHmx1zrzhDmRbqHKPyt/8OUPv3wPlf0lzPklAQAAA="; }
		}
	}
}