namespace EFMigrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AutoGeneratedMigration140204090528 : DbMigration
    {
        public override void Up()
        {
            DropColumn("dbo.MyItems", "Data2");
        }
        
        public override void Down()
        {
            AddColumn("dbo.MyItems", "Data2", c => c.String());
        }
    }
}
