namespace EFMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EFAutomation.MigrationDesignerGenerator", "1.0")]
    public sealed partial class AutoGeneratedMigration140131093058 : IMigrationMetadata
    {
        //private readonly ResourceManager Resources = new ResourceManager(typeof(First));
        
        string IMigrationMetadata.Id
        {
            get { return "201401312130597_AutoGeneratedMigration140131093058"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1XS27bMBDdF+gdBK7aRU3HToA2kBOkTlwEreMgSrKnpbFDlCJVkQrss3XRI/UKHepvyZ84CYLuRHLmzUczj8O/v/+4p4tQOI8Qa67kgBx0usQB6auAy/mAJGb26TM5PXn/zr0IwoVzX8j1rRxqSj0gD8ZEx5Rq/wFCpjsh92Ol1cx0fBVSFija63a/0IMDCghBEMtx3JtEGh5CusDlUEkfIpMwMVYBCJ3v44mXojpXLAQdMR8G5GI05vOYGfRDE+dMcIY+eCBmxGFSKpOeHN9p8Eys5NyLcIOJ22UEKDdjQkPu+XEl/tQguj0bBK0Un5UEUoaHAV5gIszSupcGOSCXBlYkUOY7LFc2cOs6VhHEZnkDs0IvIA5d1aNNxVKtpmNN45c0/R5xrhIh2FRAmalaSj2jYvgGEjD5EFwzYyCWFgPSEFrWG7aGMVi9wuA5Lm6xBNbY3I6DiqwAwV+MdUqcMVv8ADk3DwOCn8QZ8QUExU6Oeic5ljUqmTh5kpHem1jpv4mVwzexcrSrmuoQLq1Kv90QyAiGcay1onpwDQvTaIxM1gNT6x0khQo4Y4ZO2lNrrZd2KsqhGecU3EQ3kJM7ZlGEuayRVb7jeBlTDT95+/NDmGFQX6+hidLb0hL2JJtD49SmK4ARj7Wxv2XKbO6HQbhGbGtWCyv15DaJqMp1IW2/M406VXfavFbP2QjDCJFI0oig9GAdHeaKns8Ei9cQ2lCJJJSbSHGbdklRdYhy8+k4GUXVQbKd/RB6bYjevhj9NkZ/X4zDNsbhvhhHbYyjdRgubdRDs9xoq94aV16zeLf1fFOktF72fqPH3bzfdk8prQbMRIiDyXnkgW0+b6mxtjtWoOP9EkPBMd5KYMwkn4E2t+on4DXb6x70GuPOM0YPqnUg/sf5g9vQd04Ye44KjZEjwIV56cghH1nsP7D4Q8gWH+tIe48VL0bqvxrS4ashHa380FcdAJo32u5RYOMkkDUjVsRUob+Zh/ns8MwhoU0MLq0/ctxz0HxeQdgnjwTfXo0VaCFzKWeqyC1GVPeoEGmkfgyGYXmzs9jwGfMNHvugdTrq3TOR2Ms4nEJwKSeJiRJzpjWEU7EytLt0u/10Elr12Z1E6eX+GiGgm9x26ER+TbgISr9HaypnA4StkZw+0CscdRFuviyRrpR8IlCevnOIQFryuYUwEgimJ9Jjj7DZt905XM2Ye84ZTkihzjEqffvmpvbRffIPDphnYaYPAAA="; }
		}
	}
}