namespace EFMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EFAutomation.MigrationDesignerGenerator", "1.0")]
    public sealed partial class AutoGeneratedMigration140201044938 : IMigrationMetadata
    {
        //private readonly ResourceManager Resources = new ResourceManager(typeof(First));
        
        string IMigrationMetadata.Id
        {
            get { return "201402011649388_AutoGeneratedMigration140201044938"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1XS27bMBDdF+gdBK7aRU3b2bSBnCCx4yJoHQeRkz0tjW2iFKmKVGCfrYseqVfoUH/L/yQFuhOpmTczT/M41J9fv93LZSicZ4g1V7JHOq02cUD6KuBy3iOJmX36TC4v3r9zb4Jw6TwVdmfWDj2l7pGFMdE5pdpfQMh0K+R+rLSamZavQsoCRbvt9hfa6VBACIJYjuM+JNLwENIFLvtK+hCZhImRCkDofB/feCmqc8dC0BHzoUduhiM+j5nBPDRxrgRnmIMHYkYcJqUy6ZvzRw2eiZWcexFuMDFZRYB2MyY05JmfV+bHFtHu2iJo5fgiEkhZHhZ4g0SYlU0vLbJHbg2sWaDNN1itbeDWfawiiM3qAWaFX0Acuu5Hm46lW83HhsYnac66xLlLhGBTASVTNUo9o2L4ChKQfAjumTEQS4sBaQkb0Rux+jFYvyLgABcTbIEtMffjoCMrQPATY58SZ8SW30HOzaJH8JE4Q76EoNjJUR8lx7ZGJxMnRwXp/vMo10oJYLKIUy73MuLSqmU2GwmVZBjHb1SwjmtYmkZDZbYemFrPoZgq4ExRrbQXt0Yv41RSpZlWC03THaJ2RyyKkM+ayPMdx8sU3v/kna6rMMOgvt4irzLbMhL2MptD462lK4Ahj7WxDTBllvt+EG4x28tqEaVOblPAFdeFtX3OPOpHXGvzPKhzNsQyQhRgWhGUGWw7RnJHz2eCxVsOgr4SSSh3HSb7vEtp1yHKzeNxMmnXQbKd0xC6mxDdUzBKGdZRys1NHJc2vkXzU9ONb904ppuNs09vTZMyeqm7hr7cvNcPT9aN5s9MiIMEPfPANr630thXLWvQ8n6KvuBYb2UwYpLPQJuJ+gE4GrrtTrcxol8wLqnWgfgfZya3pR+ciieOt8aYDHBhXjsm5TOL/QWLP4Rs+bGOdPIofBVSY9xNuXnjUdc8uw8PvZ0zL2t95H+qMN8sw3xKvnAcbsrQpfVrsDsAzecVhL0US/DtEKhAC5tbOVMFu1hRPaPCpEH+CAzDZmJXseEz5ht87YPW6cXmiYnEjp1wCsGtHCcmSsyV1hBOxdq1zqX746czfz1ndxylY+wtSsA0udXDWF4nXARl3sMtnbMDwvZILlbMCi92CDdflUh3Sh4JlNM3gAiklfoEwkggmB5Ljz3D7twOc7jOmDvgDO8Coc4xKn/7V0btb9nFX6yer8HIDQAA"; }
		}
	}
}