namespace EFMigrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AutoGeneratedMigration140201044938 : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Items", "Boolean", c => c.Boolean(nullable: false));
        }
        
        public override void Down()
        {
            DropColumn("dbo.Items", "Boolean");
        }
    }
}
