namespace EFMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EFAutomation.MigrationDesignerGenerator", "1.0")]
    public sealed partial class AutoGeneratedMigration140204084932 : IMigrationMetadata
    {
        //private readonly ResourceManager Resources = new ResourceManager(typeof(First));
        
        string IMigrationMetadata.Id
        {
            get { return "201402042049330_AutoGeneratedMigration140204084932"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1XzW7TQBC+I/EO1p7gQDYNF6gcUEkbVEFahAv3iT1JV+yP8a6r5Nk48Ei8ArP+j/PTpoDEzbue+Wbm83w7618/foZvV0oGd5hZYfSYnQyGLEAdm0To5ZjlbvHiFXv75umT8CJRq+BrbffS25GntmN261x6yrmNb1GBHSgRZ8aahRvERnFIDB8Nh6/5yQlHgmCEFQTh51w7obBY0HJidIypy0HOTILSVvv0JipQgytQaFOIccwupme5MwocJcKCMymAcohQLlgAWhtXvDj9YjFymdHLKKUNkDfrFMluAdJilflpa/7QIoYjXwRvHR9FAmvKowIviAi39ukVRY7ZpcMNC7L5gOuNDdr6lJkUM7f+jIvaL2EB3/TjfcfGrePjQ9OTdi9HLLjKpYS5xIapDqWRMxm+R40ZOEw+gXOYaY+BRQlb0XuxJhl6vzrgOS1uqAV2xDyMQ45Qg9Anpj5lwQxWH1Ev3e2Y0SMLpmKFSb1ToX7RgtqanFyWPyjI6J9HeWeMRNB1nGZ5kJGQty2z3UikJAeCvlHNOq1x5XoNVdpG6Do9Z1nQApeKGhS9uDN6E6eVKi+1Wmua7xF1OIM0JT47Iq92gqhU+ORFdLyuVInBY7tDXk22TSTqZVhi762nK8GpyKzzDTAHz/0kUTvMDrJaR+mS2xdwy3Vt7Z9Lj+4RN9g+D7qcTakMRQIsKsImg13HSOUYxSAh23EQTIzMld53mBzybqTdhWg2H45TSrsLUu4chzDahhgdg9HIsIvSbG7jhLz3Lfqfmm99694x3W+cQ3rrmzTRG9319BVWvX7/ZN1q/tKEBUTQnUh840drS3018AaD6LucSEH1tgYz0GKB1t2Yb0ijYTQ8GfVG9CPGJbc2kf/jzBS+9Hun4pHjrTcmE1q4Px2T+g6y+BayZwpWz7tIR4/CP0Lqjbu5cH951PXP7vuH3t6ZV7Y+8T83lG+Z4WxdzclHDsRtIYa8exEOz9GKZQvhr8UaYz8FWtDa5lIvTM0v1dTNqDbp0T9DB9ROcJY5sYDY0esYrS2uNl9B5n7wqDkml/o6d2nuzqxFNZcbF7uQH45fTP3NnMPr1K/s3yiB0hReEdf6XS5k0uQ93dE7eyB8l1Rypazoakdwy3WDdGX0A4Eq+s4xRe3FfoMqlQRmr3UEd7g/t/s53GQsPBewzEDZCqP19/9l3P+YvfkNC2D81coNAAA="; }
		}
	}
}