namespace EFMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EFAutomation.MigrationDesignerGenerator", "1.0")]
    public sealed partial class AutoGeneratedMigration140214020845 : IMigrationMetadata
    {
        //private readonly ResourceManager Resources = new ResourceManager(typeof(First));
        
        string IMigrationMetadata.Id
        {
            get { return "201402141408461_AutoGeneratedMigration140214020845"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAN1YzXLbNhC+dybvwOEpPUSQpUvroZJxZKvjaWR7QiV3iFzKmIAAS4Cq9Gw59JH6Cl3wXyAlS3LcSXLhEODut7/8sOS/X//x3m1i7qwhVUyKiXsxGLoOiECGTKwmbqajN7+5796++sW7CeON87mSGxs51BRq4j5qnVwSooJHiKkaxCxIpZKRHgQyJjSUZDQc/k4uLggghItYjuN9zIRmMeQLXE6lCCDRGeVzGQJX5T4+8XNU547GoBIawMS9maH0GlBfCte54oyiDz7wyHWoEFJT8+DykwJfp1Ks/AQ3KF9sE0C5iHIFpeeXjfixQQxHJgjSKJ6VBLcODwO8wUD01riXB4nxFRt/y7YYCv4J250N3HpIZQKp3n6EqFS+DV2H7OoRW7FWa+kY+3gn9HjkOncZ53TJoU5XK6++lin8AQJSqiF8oFpDKgwG5G53rFu2zLWyhvXBJnOdOd18ALHSjxMXb11nxjYQVjulB58Ew55EJZ1msGvEI00KDyb2VkP8M+Z0moLRqwxe42LBTJo7Ng/joCL9xrXpGnkvJQcqKjv18kRfS73Rc3FMzOMXDxpJjUWsr0THNzKSnqYMe6SqOq5ho62GLmR90DaZgHKdBr4gzEFDNXYANo55d/oQ8neqN4ra34bLSUHmFemTPazvzWmSYCFap0C54/jFETB9459OvHGBQQLVw7+1t7UlfCfpCqynJu0hzFiqtOmcJTWtMA3jHrGD1amsdItk01GT8UrH3Jd6rZNwsOfYaKdvhhHFKJ4HB7Uze4+cUtsPKKdpD8FNJc9isY8kD2kXx0Bbv9jpInjEct5OEOlkyKJqO+lHlaTo97OL0T1qjqpDv9rLlKA+NdoQ9ebxOMWp0QYpdo5HqLm7DVJvnowz6gUanRrTuBvU+BSMhvPbMM3u/9zqHVq2RWrrNT1bNOyVlPj0hN7hyELEdTBFaxYafvS3Cnt9YAQG/l98yhnG2wjMqWARKL2QXwAnodHwYmSN+meM3USpkH+3szcz8T85CZ443rTHbbGmafBI09cx3fzaRvrhRuoXSZU1RYe40M+dok9I+ZOT8pLpZ0/J52DsTMjPCsiegvtSfGovdqdiezw7cj4+PB0XBIYuL3GxKFydbz/Iwu1ckJkJ+4gpeu8Q3W/jAVIlBeXlAH7mpN2lbo+0f8F416DYqoEwP2QEBGaWaUArmVsRyaq0GFvbo0rErjxoitWmV6lmEQ00Pg5Aqfxj6zPlmSlEvITwVtxnOsn0lVIQL/nOl69HDtvPPyd2ffbuE7NS3yIEdJOZhr0X7zPGw9rvWfcd2gdherMkLPQKPzYRbrWtke6kOBKoTN81JCAM3S0gTjiCqXvh0zXs9+3pHO5mzLtmdJXSWJUYjb75I0jML8G3/wGQIqk/RBQAAA=="; }
		}
	}
}