namespace EFMigrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AutoGeneratedMigration140211054506 : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.MyLollableEntities",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        Name = c.String(),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.MyPersonalItems",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        Created = c.DateTime(nullable: false),
                        Data = c.String(),
                        Boolean = c.Boolean(nullable: false),
                        Boolean2 = c.Boolean(nullable: false),
                        Data3 = c.String(),
                        Modified = c.DateTime(),
                    })
                .PrimaryKey(t => t.Id);
            
        }
        
        public override void Down()
        {
            DropTable("dbo.MyPersonalItems");
            DropTable("dbo.MyLollableEntities");
        }
    }
}
