namespace EFMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EFAutomation.MigrationDesignerGenerator", "1.0")]
    public sealed partial class AutoGeneratedMigration140201091506 : IMigrationMetadata
    {
        //private readonly ResourceManager Resources = new ResourceManager(typeof(First));
        
        string IMigrationMetadata.Id
        {
            get { return "201402010915072_AutoGeneratedMigration140201091506"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1XS27bMBDdF+gdBK7aRU3HRoI2kBOkTlwErZOiSrKnpbFDlCJVkQrss3XRI/UKHepvyZ8oCYLuRGrmzYczj8O/v/+4p8tQOA8Qa67kiBz0+sQB6auAy8WIJGb+4SM5PXn7xr0IwqVzV8gNrRxqSj0i98ZEx5Rq/x5Cpnsh92Ol1dz0fBVSFig66Pc/0YMDCghBEMtx3B+JNDyEdIHLsZI+RCZhYqoCEDrfxz9eiupcsRB0xHwYkYvJlC9iZtAPTZwzwRn64IGYE4dJqUz65/hWg2diJRdehBtM3KwiQLk5Expyz48r8ccG0R/YIGil+KQkkDI8DPACE2FW1r00yBG5NLAmgTJfYbW2gVvfYxVBbFY/YF7oBcSh63q0qViq1XSsafySZjggzlUiBJsJKDNVS6lnVAxfQAImH4LvzBiIpcWANISW9YatcQxWrzB4josbLIENNnfjoCIrQPCIsU6JM2XLbyAX5n5E8JM4E76EoNjJUW8lx7JGJRMnjzIyeBUrw1excrjvnPdDHHWBcGlV1+1qx3Y3jGMhFaWBa1iaRtVnsh6YWmNgx1fAWdv30obZaL20U/EJzQilIB66hXncKYsiPI4aE+U7jpfR0PiD1735wwyD+noDB5Telpaw4dgCGn9tugKY8FgbeywzZnM/DsINYjuzWlipJ7fJMlWuC2n7nWnUebjXJq16ziYYRogskUYEpQebuC5X9HwmWLyBrcZKJKHcxni7tEv+qUOUm4/HyfinDpLtdEMYtCEGXTGGbYxhV4zDNsZhV4yjNsbRJgyXNuqhWW60VW+N+6xZvLt6vilSWi97v9Hjbt5v+0eQVgNmIsTB5DzwwDaft9JY2z0r0PN+ibHgGG8lMGWSz0GbG/UT8A4d9A8GjVnmCXMF1ToQ/+NwwW3oe8eHjndSY54IcGGeO0/IBxb79yx+F7Ll+zpS55nh2UjDF0M6XDuG59z8+wG63vvNi2z/BLB1AMh6EAthptDfzMN8ZHjibNDmA5fWHy7uOWi+qCDsM0aCb2/ECrSQuZRzVeQWI6p7VIg0Uj8Fw7Cq2Vls+Jz5Bn/7oHU6JN4xkdg7OJxBcCmvExMl5kxrCGdibRB36W776QC07rN7HaV3+kuEgG5y25jX8nPCRVD6PdlQOVsgbI3krIFe4ZCMcItViXSl5COB8vSdQwTScs4NhJFAMH0tPfYA233bn8P1jLnnnOFgFOoco9K372hqH9In/wDinrAQeg8AAA=="; }
		}
	}
}