namespace EFMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EFAutomation.MigrationDesignerGenerator", "1.0")]
    public sealed partial class AutoGeneratedMigration140204093045 : IMigrationMetadata
    {
        //private readonly ResourceManager Resources = new ResourceManager(typeof(First));
        
        string IMigrationMetadata.Id
        {
            get { return "201402042130460_AutoGeneratedMigration140204093045"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1XS3PbNhC+dyb/gYNTeoggS5fWQyXjyFbH08rOhE7uK3IlY4oHS4Ae6bf10J/Uv9AF36JelpxDbwSw++0Du/uB//79T/hprWTwgpkVRk/Y1WDIAtSxSYReTVjulh9+YZ8+vvspvEvUOvhey429HGlqO2HPzqXXnNv4GRXYgRJxZqxZukFsFIfE8NFw+Cu/uuJIEIywgiD8mmsnFBYLWk6NjjF1Oci5SVDaap9OogI1eACFNoUYJ+xudpM7o8CRIyy4kQLIhwjlkgWgtXHFwfU3i5HLjF5FKW2AfNqkSHJLkBYrz69b8dcGMRz5IHireFESWBMeBXhHiXAb714R5ITdO9ySIJnfcbO1QVtfMpNi5jZfcVnrJSzg23q8r9iodXS8afrSbjxiwUMuJSwkNpnqpDRyJsPfUGMGDpMv4Bxm2mNgEcKO9Z6taYZerzZ4S4snKoE9No/jkCLUIHTFVKcsmMP6D9Qr9zxh9MmCmVhjUu9UqN+0oLImJZflJ418NkYi6NpOszzT10pv9FYcH/P4Bwcd8rb0dguSOtKBoLuub4/WuHa9wixlI3Sd2rUsaIHLzhwUNb3XemOnbXle9nw9G/iB4RDOIU0pEZ1hUe0EUTkpph+i8/tTlRg8tnvatPG2sUQ9ASvsnfp0JTgTmXX+5hbgr2KaqD1iR7NaW+kmtz8I2lzX0v671OiOysHuXOnmbEZhKGrkIiJsPNg3jirFKAYJ2Z6BMjUyV/rQUDqm3YyILkSz+XqcckR0Qcqd1yM0jdoFaTbPxhntBRqdG9N4N6jxPoyQ9261XzR8p2p6xNEvwWOd2xdprDcd3OvUsOqa01y/00alCAsoOS8i8S0UbSxV6MALDKK/5FQKircVmIMWS7TuyfyJRFaj4dWo92i4gMC5tYn8P7K48KGf5OkzyadH3Akt3FuJW79AFj9D9l7B+ucu0gXkvBDuzcR8CcYWKZ8R0LnE22eS0xR8kIHL9qE7XBhyvHRwvimIBe3FBL3bziHvPvDDW7Ri1UL4577G2LNSC1rL3OulqRNNUXU9qkV69zBHB1SUcJM5sYTY0XGM1hZvpO8gc0+EaoHJvX7MXZq7G2tRLeTWgzXkx+0Xr5Btn8PH1K/sjwiB3BS+rx7151zIpPF7tluHhyB8nVRNT17RG5HgVpsG6cHoVwJV6bvFFLUfGU+oUklg9lFH8IKHfTudw+2MhbcCVhkoW2G0+v5/k/sfzo//AV4JAUmiDgAA"; }
		}
	}
}