namespace EFMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EFAutomation.MigrationDesignerGenerator", "1.0")]
    public sealed partial class AutoGeneratedMigration140204091801 : IMigrationMetadata
    {
        //private readonly ResourceManager Resources = new ResourceManager(typeof(First));
        
        string IMigrationMetadata.Id
        {
            get { return "201402042118018_AutoGeneratedMigration140204091801"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1XS3PbNhC+dyb/gYNTeoggS5fWQyXjyFbH08rOhE7uK3IlY4oHS4Ae6bf10J/Uv9AF36JelpxDbwSw++0Du/uB//79T/hprWTwgpkVRk/Y1WDIAtSxSYReTVjulh9+YZ8+vvspvEvUOvhey429HGlqO2HPzqXXnNv4GRXYgRJxZqxZukFsFIfE8NFw+Cu/uuJIEIywgiD8mmsnFBYLWk6NjjF1Oci5SVDaap9OogI1eACFNoUYJ+xudpM7o8CRIyy4kQLIhwjlkgWgtXHFwfU3i5HLjF5FKW2AfNqkSHJLkBYrz69b8dcGMRz5IHireFESWBMeBXhHiXAb714R5ITdO9ySIJnfcbO1QVtfMpNi5jZfcVnrJSzg23q8r9iodXS8afrSbjxiwUMuJSwkNpnqpDRyJsPfUGMGDpMv4Bxm2mNgEcKO9Z6taYZerzZ4S4snKoE9No/jkCLUIHTFVKcsmMP6D9Qr9zxh9MmCmVhjUu9UqN+0oLImJZflJ418NkYi6NpOszzT10pv9FYcH/P4Bwcd8rb0dguSOtKBoLuub4/WuHa9wixlI3Sd2rUsaIHLzhwUNb3XemOnbXle9nw9G/iB4RDOIU0pEZ1hUe0EUTkpph+i8/tTlRg8tnvatPG2sUQ9ASvsnfp0JTgTmXX+5hbgr2KaqD1iR7NaW+kmtz8I2lzX0v671OiOysHuXOnmbEZhKGrkIiJsPNg3jirFKAYJ2Z6BMjUyV/rQUDqm3YyILkSz+XqcckR0Qcqd1yM0jdoFaTbPxhntBRqdG9N4N6jxPoyQ9261XzR8p2p6xNEvwWOd2xdprDcd3OvUsOqa01y/00alCAsoOS8i8S0UbSxV6MALDKK/5FQKircVmIMWS7TuyfyJRFaj4dWo92i4gMC5tYn8P7K48KGf5OkzyadH3Akt3FuJW79AFj9D9l7B+ucu0gXkvBDuzcR8CcYWKZ8R0LnE22eS0xR8kIHL9qE7XBhyvHRwvqlY+0J63m3mkHef9+EtWrFqIfxjX2PsOakFrWXu9dLUaaaYuh7VIr1bmKMDKkm4yZxYQuzoOEZrixfSd5C5p0G1wOReP+Yuzd2NtagWcuu5GvLj9os3yLbP4WPqV/ZHhEBuCt9Vj/pzLmTS+D3brcJDEL5KqpYnr+iFSHCrTYP0YPQrgar03WKK2g+MJ1SpJDD7qCN4wcO+nc7hdsbCWwGrDJStMFp9/7fJ/e/mx/8AfSZMRaAOAAA="; }
		}
	}
}