namespace EFMigrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AutoGeneratedMigration140131093410 : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Items", "Data6", c => c.Int(nullable: false));
        }
        
        public override void Down()
        {
            DropColumn("dbo.Items", "Data6");
        }
    }
}
