namespace EFMigrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AutoGeneratedMigration140204091801 : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.MyItems", "Boolean2", c => c.Boolean(nullable: false));
        }
        
        public override void Down()
        {
            DropColumn("dbo.MyItems", "Boolean2");
        }
    }
}
