namespace EFMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EFAutomation.MigrationDesignerGenerator", "1.0")]
    public sealed partial class AutoGeneratedMigration140131092827 : IMigrationMetadata
    {
        //private readonly ResourceManager Resources = new ResourceManager(typeof(First));
        
        string IMigrationMetadata.Id
        {
            get { return "201401312128281_AutoGeneratedMigration140131092827"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1XzXLaMBC+d6bv4NGpPRQRyKHNmGRSEjqZlpCJk9yFvRBNZcm15Aw8Ww99pL5CV/7HBgIkk+nNkne//dF+u9Lf33/cs0UonCeINVdyQI46XeKA9FXA5XxAEjP79Jmcnb5/514G4cJ5KOT6Vg41pR6QR2OiE0q1/wgh052Q+7HSamY6vgopCxTtdbtf6NERBYQgiOU47m0iDQ8hXeByqKQPkUmYGKsAhM738Y+XojrXLAQdMR8G5HI05vOYGfRDE+dccIY+eCBmxGFSKpP+ObnX4JlYybkX4QYTd8sIUG7GhIbc85NKfNcguj0bBK0UD0oCKcPDAC8xEWZp3UuDHJArAysSKPMdlisbuHUTqwhis7yFWaEXEIeu6tGmYqlW07Gm8Uuafo8414kQbCqgzFQtpZ5RMXwDCZh8CG6YMRBLiwFpCC3rDVvDGKxeYfACF3dYAmtsbsdBRVaA4BFjnRJnzBY/QM7N44DgJ3FGfAFBsZOj3kuOZY1KJk52MtJ7Eyv9N7Fy/MpWXFrVbbuakc6GcSyU4uhxDQvTqOpM1gNTK3xkdAWc0bqTEmKt9dJO1S9o1jCKxkI3dBZ3zKIIE1HrNPmO42VtZvjJ25/cYYZBfb2G46W3pSUkFJtD469NVwAjHmtjT27K7FEMg3CN2NasFlbqyW12kSrXhbT9zjTqfbbTbkr1nI0wjBC7QBoRlB6s62W5ouczweI13WioRBLKTR1tm3bZX+oQ5ebuOFl/qYNkO/sh9NoQvX0x+m2M/r4Yx22M43UYLm2cZbNUaKtWGrOmWXjb+NoUKa2XvG3w08258vz1oEWeTIQ4mJwnHljieEuNddmxAh3vlxgKjvFWAmMm+Qy0uVM/Aedbr3vUa9wzDpj5VOtA/I+Dn9vQnx3te87oxqwPcGFeOuvlE4v9RxZ/CNniYx1p73n+YqT+qyEdH4C07+xtDpPnp/DGIZxxCQ90qtDxzMF8bB84n9u8dmn9ceBegObzCsI+FST4dipVoIXMlZypIskYUd2jQqRxBmMwDKuTnceGz5hv8LcPWqdXpAcmEjsHwykEV3KSmCgx51pDOBUrl12XbrefXkJWfXYnUTpXXyMEdJNbgk3k14SLoPR71CbYJghbIzn70Su8IiLcfFkiXSu5I1CevguIQNrecQdhJBBMT6THnmCzb8/ncDVj7gVneDkJdY5R6du3KrWP1dN/ydwL194OAAA="; }
		}
	}
}