namespace EFMigrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AutoGeneratedMigration140204093045 : DbMigration
    {
        public override void Up()
        {
            RenameTable(name: "dbo.MyItems", newName: "MyItemses");
        }
        
        public override void Down()
        {
            RenameTable(name: "dbo.MyItemses", newName: "MyItems");
        }
    }
}
