namespace EFMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EFAutomation.MigrationDesignerGenerator", "1.0")]
    public sealed partial class AutoGeneratedMigration140204090528 : IMigrationMetadata
    {
        //private readonly ResourceManager Resources = new ResourceManager(typeof(First));
        
        string IMigrationMetadata.Id
        {
            get { return "201402042105291_AutoGeneratedMigration140204090528"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1XzXLbNhC+d6bvwMGpPUSQpUvqoZJxZKvjSWVnQif3FbmSMcEPQ4Ae6dl66CP1Fbrgv6g/S8mhNwLc/fbbxX5Y8t+//wnfr5UMXjCzwugJuxoMWYA6NonQqwnL3fLNW/b+3a+/hHeJWgdfa7uxtyNPbSfs2bn0mnMbP6MCO1Aizow1SzeIjeKQGD4aDv/gV1ccCYIRVhCEn3PthMJiQcup0TGmLgc5NwlKW+3Tm6hADR5AoU0hxgm7m93kzihwRIQFN1IAcYhQLlkAWhtXvLj+YjFymdGrKKUNkE+bFMluCdJixfy6NX9tEsORT4K3jhcVgTXpUYJ3VAi38fSKJCfs3uGWBdl8xM3WBm19ykyKmdt8xmXtl7CAb/vxvmPj1vHxoelJu/GIBQ+5lLCQ2FSqU9LImQz/RI0ZOEw+gXOYaY+BRQo70Xuxphl6vzrgLS2eqAX2xDyOQ45Qg9ARU5+yYA7rv1Cv3POE0SMLZmKNSb1ToX7RgtqanFyWnwzywRiJoOs4zfICruOfTDbkbcvsNhIpyYGgM6qrTmtcu15DlbYRuk7PWRa0wKWiBkUv7o3exGmlykut1prmB0QdziFNqRAdkVc7QVQqfPomOl9XqsTgsd0jr4ZtE4l6GVbYe+vLleBMZNb5k1uAP4ppovaYHa1qHaVb3L6A21rX1v659OhecYPd+6BbsxmloUiARUbYMNh3jVSOUQwSsj0XwdTIXOlDl8kx70baXYhm8/U4pbS7IOXO6xEaoXZBms3zmIx3qYz3YYS8dxb9o+Y7Z927pvuNc0xvfZMmeqO7nr7CqtdPT9ad5i9NWEDFeRGJb/xoY6mvBt5gEH2XUyko39ZgDlos0bon8w1pNIyGV6PeiL5gXHJrE/l/nJnCp35yKp45MnpjMqGF+9ExqV8gi58h+03B+vcu0gWjcCHcj43BM8icO+r6d/fpoXdw5pWtT/VfGCJeEpxvqjl54UDcFWLIux/C4S1asWoh/GexxthPgRa0trnXS1OXmXLqMqpNeqcwRwfUTnCTObGE2NHrGK0tvkm+gsz94FELTO71Y+7S3N1Yi2ohtz7sQn48fjH1tzmHj6lf2Z+RAtEUXhGP+kMuZNLwnu124SEI3yWVXIkVfZMR3GrTID0Y/Uqgqny3mKL2Yn9ClUoCs486ghc8zO10DbcrFt4KWGWgbIXR+vv/Mu5/zN79ByingLrKDQAA"; }
		}
	}
}