namespace EFMigrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AutoGeneratedMigration140201044633 : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Items", "Data2", c => c.String());
        }
        
        public override void Down()
        {
            DropColumn("dbo.Items", "Data2");
        }
    }
}
