namespace EFMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EFAutomation.MigrationDesignerGenerator", "1.0")]
    public sealed partial class AutoGeneratedMigration140211054506 : IMigrationMetadata
    {
        //private readonly ResourceManager Resources = new ResourceManager(typeof(First));
        
        string IMigrationMetadata.Id
        {
            get { return "201402111745072_AutoGeneratedMigration140211054506"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAN1Yy3LbNhTddyb/wOEqXUSQpU3roZJxZKvjaWR7QiV7iLyUMQEBlgBV6duy6Cf1F3rBt0BKluS4k2SjEcF7z32BB4f89+s/3rtNzJ01pIpJMXEvBkPXARHIkInVxM109OY3993bV794N2G8cT5XdmNjh55CTdxHrZNLQlTwCDFVg5gFqVQy0oNAxoSGkoyGw9/JxQUBhHARy3G8j5nQLIb8Ai+nUgSQ6IzyuQyBq3Id7/g5qnNHY1AJDWDi3szQeg3oL4VynSvOKCbhA49chwohNTV3Lj8p8HUqxcpPcIHyxTYBtIsoV1CmftmYH1vFcGSqII3jWV1w6/qwwhusRG9NenmVWGCx8Ldsm6Hhn7DdWcClh1QmkOrtR4hK59vQdciuH7Eda7eWj4mP/4Qej1znLuOcLjnU7Wr11dcyhT9AQEo1hA9Ua0iFwYA87U50K5b5raLhfHCXuc6cbj6AWOnHiYt/XWfGNhBWK2UGnwTDTYlOOs1gN4hHmhYebOythvhn7Ok0BeNXBbzGiwUzbe7EPIyDjvQbz6Yb5L2UHKio4tSXJ+Za+o2ei2NqHr940chqLGJ9Izp+IyPracpwj1RTx2vYaGtDF7Y+aJtMALmygS8Ic9BQjV2AjWOenT6E/JnqraLOtyFzUrB5xfpkD+17c5okOIjWMVCuOH5xBkzf+KcTb1xgkED18G+dbR0Jn0m6AuuuaXsIM5YqbXbOkpqtMA3jHrOD06midIdk01HT8crH/C/92kfhYM+50e7fDEuK0T6vDups9p45pbcfUE7THoabSp7FYh9LHvIuzoG2f7HSRfCIlbzdIdJpkcXVdtePmkmx4c+fRvewOWoQ/W4vM4P63GhD1IvH4xTnRhukWDkeoWbvNki9eDLOqBdodGpN425R41MwGtZvwzSr//Ne7xCzbVJHrwnaImKvJMWnRXqHJQsT18EWrVloGNLfKtzrA2Mw8P/iU86w3sZgTgWLQOmF/AKohUbDi5El9s8Q3kSpkH+36puZ+p/UgicKnLbgFmuaBo80fR3Tza9tpB9OVL9IqywdHeKFfq6OPqHlT2rlJdPP1snnYOxo5GcVZOvgvhafuhe7utgWaEcq5MP6uCAwTHmJF4si1fn2gyzSzg2Z0dhH6Oi9Mro/xgOkSgrKSwl+ptbuUrdH2l9hvGtQbNVAmG8yAgIjZhrQyuZWRLIaLdbWzqgysScPmuK06VWqWUQDjbcDUCp/3fpMeWYGES8hvBX3mU4yfaUUxEu+8+7rkcPx8xeK3Zy9+ySXY9+iBEyTmQ17L95njId13rPuM7QPwuzNkrAwK3zdRLjVtka6k+JIoLJ915CAMHS3gDjhCKbuhU/XsD+3p3u42zHvmtFVSmNVYjT+5qMgMV8F3/4HeoTTRkcUAAA="; }
		}
	}
}