namespace EFMigrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AutoGeneratedMigration140201094440 : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Items", "TestBool", c => c.Boolean(nullable: false));
        }
        
        public override void Down()
        {
            DropColumn("dbo.Items", "TestBool");
        }
    }
}
