namespace EFMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EFAutomation.MigrationDesignerGenerator", "1.0")]
    public sealed partial class AutoGeneratedMigration140201044633 : IMigrationMetadata
    {
        //private readonly ResourceManager Resources = new ResourceManager(typeof(First));
        
        string IMigrationMetadata.Id
        {
            get { return "201402011646337_AutoGeneratedMigration140201044633"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1XzXLaMBC+d6bv4NGpPQQBubQZk0wKoZNpCZmY5C7sBTSVJdeSGXi2HvpIfYWu/I/5T3PozZZ3v939tJ9W/vPrt3uzCoWzhFhzJXuk02oTB6SvAi7nPZKY2cUncnP9/p17F4Qr56Wwu7R26Cl1jyyMia4o1f4CQqZbIfdjpdXMtHwVUhYo2m23P9NOhwJCEMRyHPcpkYaHkL7ga19JHyKTMDFSAQidr+MXL0V1HlgIOmI+9MjdcMTnMTOYhybOreAMc/BAzIjDpFQm/XL1rMEzsZJzL8IFJibrCNBuxoSGPPOryvzUItpdWwStHF9FAinLwwLvkAiztumlRfbIvYENC7T5BuuNBVx6jFUEsVk/wazwC4hDN/1o07F0q/nY0PgkzWWXOA+JEGwqoGSqRqlnVAxfQQKSD8EjMwZiaTEgLWEreiNWPwbrVwQc4MsEW2BHzMM46MgKENxi7FPijNjqO8i5WfQIPhJnyFcQFCs56rPk2NboZOLkpCDdN47i0mqvtzsAJWAYR3ILuvAdVqbRCZmtB6bWLKiCCjiTQittop3RyziVxmgmskKMdI8a3RGLIiSips58xfEyafYvvPMFEWYY1Nc7dFFmW0bCJmRzaHy1dAUw5LE2duemzG5FPwh3mB1ktYhSJ7epvIrrwto+Zx71s6m1LeQ6Z0MsI0TlpBVBmcEu/eeOns8Ei3couK9EEsp9p8Ah71KTdYhy8XScTJN1kGzlPITuNkR3F4ZLGxw2t4hu7VHjXGxu+CGdNE3K6KVeGrpw8x49Psq2mjYzIQ6Ss+SBbVhvrbEfWtag5f0UfcGx3spgxCSfgTYT9QPwLO62O93GTHzFfKJaB+J/HFLcln50DJ05TxpzKcAX869zSS5Z7C9Y/CFkq491pLNnzxlI586X5oF5fNLsHTRZ3yJ5U4WJZwnmo+mVM2hbQy6tXxrdAWg+ryDsFVKCb0/eCrSwuZczVZCMFdUzKkwaezACw7AT2G1s+Iz5Bj/7oHV6DXhhIrFnfTiF4F6OExMl5lZrCKdi4xLk0sPx00G7mbM7jtLZ8RYlYJrcNvNYfkm4CMq8h9vNvA/C9kiuNMwKr0EIN1+XSA9KngiU0zeACKTV6QTCSCCYHkuPLWF/bsc53GTMHXCGAzjUOUblb/9hqP2Juf4LH2izmPYMAAA="; }
		}
	}
}