namespace EFMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EFAutomation.MigrationDesignerGenerator", "1.0")]
    public sealed partial class AutoGeneratedMigration140204085335 : IMigrationMetadata
    {
        //private readonly ResourceManager Resources = new ResourceManager(typeof(First));
        
        string IMigrationMetadata.Id
        {
            get { return "201402042053356_AutoGeneratedMigration140204085335"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1XzW7jNhC+F+g7CDy1hzUd+9IG8i6yTlwErZPFKrv3sTR2iPJHFanAfrYe9pH6Ch3q35LtxMkW6E0kZ7754cx81D9/fws/bJUMnjCzwugZuxiNWYA6NonQmxnL3frdL+zD+x9/CG8StQ2+1nJTL0ea2s7Yo3PpJec2fkQFdqREnBlr1m4UG8UhMXwyHv/KLy44EgQjrCAIP+faCYXFgpZzo2NMXQ5yaRKUttqnk6hADe5AoU0hxhm7WVzlzihw5AgLrqQA8iFCuWYBaG1ccXD5xWLkMqM3UUobIB92KZLcGqTFyvPLVvylQYwnPgjeKr4qCawJjwK8oUS4nXevCHLGbh3uSZDM77jb26CtT5lJMXO7z7iu9RIW8H093lds1Do63jR9aTedsOAulxJWEptMdVIaOZPhb6gxA4fJJ3AOM+0xsAhhYL1na56h16sNXtPigUrggM3TOKQINQhdMdUpC5aw/QP1xj3OGH2yYCG2mNQ7FeoXLaisScll+YuMTP5zKx+NkQi6ttMsX5GR6Xd2NuRtYQ7LlfrVgaBKqO+W1rh1vbItZSN0ncq2LGiBy74dFRV/0Hpjpx0IvJwI9eTgR0ZHuIQ0pUR0Rkm1E0TlHJm/i87vXlVi8NgeaOLG28YSdQxssHfq05XgQmTW+Ztbgb+KeaIOiJ3Mam2lm9z+mGhzXUv771KjO0hHw6nTzdmCwlDU5kVE2HhwaFhVilEMErID42ZuZK70sZF1SrsZIF2IZvPlOOUA6YKUO+chTIYQk3MwmmbvojSb5/kyHfoyPYQR8t599suFD+qlRyj94jvVs32RxnrTu70eDat+ef4NMGigUoQFlJwnkfjmiXaWanPkBUbRX3IuBcXbCixBizVa92D+RCKxyfhi0ntMvILYubWJ/D+yu/ChP8vfZ9JOj9ATWri3Erp+gix+hOwnBdufu0hnk/abkHrEvBLubaR8hjPnEm+fSZ6n4KMMXDYR3eTKkOOlg8tdxdqvpOdhS4e8+/gPr9GKTQvhfwU0xp6TWtBa5lavTZ1miqnrUS3Su4UlOqDChKvMiTXEjo5jtLZ4IX0FmXsaVCtMbvV97tLcXVmLaiX3HrMhP22/eIPs+xzep35lv0cI5KbwvXWvP+ZCJo3fi2EVHoPwVVI1PnlFL0SC2+wapDujXwhUpe8aU9R+bDygSiWB2XsdwRMe9+35HO5nLLwWsMlA2Qqj1ff/otz/jL7/F+qFNn++DgAA"; }
		}
	}
}