namespace EFMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EFAutomation.MigrationDesignerGenerator", "1.0")]
    public sealed partial class AutoGeneratedMigration140201044610 : IMigrationMetadata
    {
        //private readonly ResourceManager Resources = new ResourceManager(typeof(First));
        
        string IMigrationMetadata.Id
        {
            get { return "201402011646103_AutoGeneratedMigration140201044610"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1WyW7bMBC9F+g/CDy1h5i2c2kDOUFqx0XQOg4iJ3daGtlEKVIVKcP+th76Sf2FDrVb3rL00Js4mnmzvRnyz6/f7tU6Es4KEs2VHJBep0sckL4KuFwMSGrCs0/k6vL9O/cmiNbOU6l3bvXQUuoBWRoTX1Cq/SVETHci7idKq9B0fBVRFija73Y/016PAkIQxHIc9yGVhkeQHfA4VNKH2KRMTFQAQhdy/ONlqM4di0DHzIcBuRlP+CJhBuPQxLkWnGEMHoiQOExKZbI/F48aPJMoufBiFDAx28SAeiETGorIL2r15ybR7dskaG34qiKQKj1M8AYLYTY2vCzJAbk1sKWBOt9gsyVA0X2iYkjM5gHC0i4gDt22o23DyqxhY13jlzTnfeLcpUKwuYCqUo2SekYl8BUkYPEhuGfGQCItBmQp7Hhv+RomYO1KhyM8zJACe3wex0FDVoJgi5GnxJmw9XeQC7McEPwkzpivISglBeqj5EhrNDJJ2nLi0roLu71BchrGMe0yETzD2rR6lOt6YBptRH7WwDlJO1l793qv/NTspzn9yzGhB+bEnbA4xkI05qaQOF4+NMMz7+VUjXIM6us9jK2irTwhPdgCWn9tuQIY80Qb27g5s60YBtEetaNVLb00i9ueibrWpbb9zi2aW6OzO2LNmo0xjQg5nWUEVQT7JrMw9HwmWLJntoZKpJE8NJ/HrKtpaUJUwufj5NPSBMkluwgubeXfLi/dqW9r27SbdYzjbZXKe8X1Fqfdgl+nL4gdwuUqxMHSrHhgyeZtNPayYxU63k8xFBzzrRUmTPIQtJmpH4Abrt/t9Vs3zSu2PtU6EP/j6uc29ZPL/YVburXtAzyYt257uWKJv2TJh4itPzaR3r7R2yvq9G4/uNpztmHKc4WB5wEWl8Ert/4u813afEC5I9B8UUPY55QE3+66GrTUuZWhKmuMGTUjKlVaLZiAYdg/dp0YHjLf4G8ftM4u3icmUrtdozkEt3Kamjg111pDNBdbDwKXHvefXW3bMbvTONvW/yIFDJNbCk7ll5SLoIp7vEvBQxCWI8V8YFT48EC4xaZCulPymUBF+UYQg7TTNYMoFgimp9JjKzgc2+kablfMHXGGV16kC4za3r7nqX3QX/4FHbQy/wIMAAA="; }
		}
	}
}