using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Data.Entity.Migrations.Design;
using System.Data.Entity.Migrations.Infrastructure;
using System.Data.Odbc;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using Core;
using EFAutomation.Exceptions;
using Microsoft.CSharp;

namespace EFAutomation
{
    public class AutoContextFactory : IAutoContextFactory
    {
        private int _migrationAttempts;

        public IAutoContextFactoryConfiguration Configuration { get; set; }

        private readonly List<Assembly> _assemblies = new List<Assembly>();
        private readonly List<Type> _subClassesOf = new List<Type>();
        private readonly List<Type> _singleClasses = new List<Type>();
        private readonly GeneratedContext _contextGenerator;
        private IContext _context;
        private IDbMigrationsConfiguration _dbMigrationsConfiguration;
        private CSharpCodeProvider _codeProvider;
        private bool _migrated = false;

        public event SeedingEventHandler Seeding;

        # region Add assemblies

        public IAutoContextFactory AddEntitiesBasedOn<T>() where T : class
        {
            _subClassesOf.Add(typeof (T));
            return this;
        }

        public IAutoContextFactory AddEntity<T>() where T : class
        {
            _singleClasses.Add(typeof(T));
            return this;
        }

        public IAutoContextFactory AddAssemblyContaining<T>() where T : class
        {
            _assemblies.Add(Assembly.GetAssembly(typeof (T)));
            return this;
        }

        public IAutoContextFactory AddAssembly(Assembly assembly)
        {
            _assemblies.Add(assembly);
            return this;
        }

        #endregion

        public AutoContextFactory()
        {
            _contextGenerator = new GeneratedContext();
            _codeProvider = new CSharpCodeProvider();
            Configuration = new AutoContextFactoryConfiguration()
            {
                AutoGeneratedMigrationsEnabled = false,
                AutoMigrateToLatestVersionEnabled = false,
                AutomaticMigrationDataLossAllowed = false,
                //CodeProvider = new CSharpCodeProvider(),
                MigrationsDirectory = "AutomaticMigrations",
                Connection = "DefaultConnection"
            };
        }

        public AutoContextFactory(IAutoContextFactoryConfiguration configuration) : this()
        {
            Configuration = configuration;
        }

        private void CompileAssembliesAndCreateClasses()
        {
            var compilerParameters = DefaultCompilerParameters();
            var types = new List<Type>();
            foreach (var assembly in _assemblies)
            {
                foreach (var entity in _subClassesOf)
                {
                    var entity1 = entity;
                    types.AddRange(assembly.GetTypes().Where(x => x.IsSubclassOf(entity1) && !x.IsAbstract));
                }
            }
            types.AddRange(_singleClasses);
            types = types.Distinct().ToList();
            compilerParameters.ReferencedAssemblies.AddRange(
                types.Select(x => Assembly.GetAssembly(x).Location).Distinct().ToArray());
            var namespaces = new List<string>();
            namespaces.AddRange(types.Select(x => x.Namespace));

            // Set variables for context generator
            _contextGenerator.Session = new Dictionary<string, object>();
            _contextGenerator.Session["Types"] = types;
            _contextGenerator.Session["Assemblies"] = namespaces;
            if (Configuration.AutoMigrateToLatestVersionEnabled)
                _contextGenerator.Session["MigrateToLatestVersion"] = true;
            _contextGenerator.Session["Connection"] = Configuration.Connection;
            _contextGenerator.Initialize();

            var generatedContextSource = _contextGenerator.TransformText();
            var contextAssembly = _codeProvider.CompileAssemblyFromSource(compilerParameters,
                generatedContextSource);
            if (contextAssembly.Errors.Count > 0)
                throw new AssemblyCompilationErrorsException(contextAssembly.Errors);

            _dbMigrationsConfiguration =
                (IDbMigrationsConfiguration)
                    contextAssembly.CompiledAssembly.CreateInstance("EFMigrations.Configuration");
            _dbMigrationsConfiguration.Seeding += DbMigrationsConfigurationOnSeeding;
            _context = (IContext)contextAssembly.CompiledAssembly.CreateInstance("EFMigrations.Context", false, BindingFlags.CreateInstance, null,
                        new object[] { "DefaultConnection" }, CultureInfo.CurrentCulture, null);
        }

        private void DbMigrationsConfigurationOnSeeding(object sender, IContext context)
        {
            if (Seeding != null)
                Seeding(sender, _context);
        }

        public IContext Context()
        {
            if(_context == null)
                CompileAssembliesAndCreateClasses();

            if(Configuration.AutoMigrateGeneratedMigrationsEnabled && !_migrated)
                MigrateToLatest();

            return _context;
        }

        public void MigrateToLatest()
        {
            if (_migrationAttempts > 2)
            {
                _migrationAttempts = 0;
                return;
            }

            try
            {
                TryMigrate();
                _migrationAttempts = 0;
            }
            catch (Exception ex)
            {
                if (!(ex is AutomaticMigrationsDisabledException) && !(ex is DirectoryNotFoundException)) throw;
                _migrationAttempts++;
                if (Configuration.AutoGeneratedMigrationsEnabled)
                {
                    GenerateMigrations();
                    MigrateToLatest();
                }
                else
                    throw new MigrationsOutOfDateException(
                        "Migrations are out of date but AutoGeneratedMigrationsEnabled is false", ex);
            }
        }

        public void GenerateMigrations()
        {
            if(_dbMigrationsConfiguration == null)
                CompileAssembliesAndCreateClasses();

            var migrationScaffolder = new MigrationScaffolder((DbMigrationsConfiguration)_dbMigrationsConfiguration) { Namespace = "EFMigrations" };
            var name = "AutoGeneratedMigration" + DateTime.Now.ToString("yyMMddhhmmss");
            var scaffoldedMigration = migrationScaffolder.Scaffold(name);
            if (!Directory.Exists(Configuration.MigrationsDirectory))
                Directory.CreateDirectory(Configuration.MigrationsDirectory);
            File.WriteAllText(Path.Combine(Configuration.MigrationsDirectory, scaffoldedMigration.MigrationId + ".cs"), scaffoldedMigration.UserCode);
            var designerGenerator = new MigrationDesignerGenerator
            {
                Session =
                    new Dictionary<string, object>
                    {
                        {"Target", scaffoldedMigration.Resources["Target"]},
                        {"MigrationId", scaffoldedMigration.MigrationId},
                        {"ClassName", name}
                    }
            };
            designerGenerator.Initialize();
            File.WriteAllText(
                Path.Combine(Configuration.MigrationsDirectory, scaffoldedMigration.MigrationId + ".Designer.cs"),
                designerGenerator.TransformText());
        }

        
        private CompilerParameters DefaultCompilerParameters()
        {
            var compilerParams = new CompilerParameters();
            compilerParams.ReferencedAssemblies.Add(Assembly.GetAssembly(typeof(DbContext)).Location);
            compilerParams.ReferencedAssemblies.Add("System.Data.dll");
            compilerParams.ReferencedAssemblies.Add("System.Data.Entity.dll");
            compilerParams.ReferencedAssemblies.Add("System.Core.dll");
            compilerParams.ReferencedAssemblies.Add("System.dll");
            compilerParams.ReferencedAssemblies.Add(Assembly.GetAssembly(typeof(IContext)).Location);
            compilerParams.GenerateInMemory = false;
            return compilerParams;
        }

        

        private void TryMigrate()
        {
            // Compile migrations assembly
            var parameters = DefaultCompilerParameters();
            _codeProvider = new CSharpCodeProvider();
            var files = Directory.GetFiles(Configuration.MigrationsDirectory).Where(x => x.EndsWith(".cs")).Select(File.ReadAllText);
            var compiled = _codeProvider.CompileAssemblyFromSource(parameters, files.ToArray());
            // Assign the assembly to migrations configuration
            _dbMigrationsConfiguration.MigrationsAssembly = compiled.CompiledAssembly;
            // Migrate
            var migrator = new DbMigrator((DbMigrationsConfiguration)_dbMigrationsConfiguration);
            migrator.Update();
            _migrated = true;
        }
        
    }
}
