using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EFAutomation
{
    public class AutoContextFactoryConfiguration : IAutoContextFactoryConfiguration
    {
        public string MigrationsDirectory { get; set; }
        public bool AutoMigrateToLatestVersionEnabled { get; set; }
        public bool AutoGeneratedMigrationsEnabled { get; set; }
        public bool AutomaticMigrationDataLossAllowed { get; set; }
        //public CodeDomProvider CodeProvider { get; set; }
        public string Connection { get; set; }
        public bool AutoMigrateGeneratedMigrationsEnabled { get; set; }
    }
}
