using System.CodeDom.Compiler;
using System.Security.Cryptography.X509Certificates;

namespace EFAutomation
{
    public interface IAutoContextFactoryConfiguration
    {
        string MigrationsDirectory { get; set; }
        bool AutomaticMigrationsEnabled { get; set; }
        bool AutomaticMigrationDataLossAllowed { get; set; }
        bool AutoGeneratedMigrationsEnabled { get; set; }
        CodeDomProvider CodeProvider { get; set; }
        string Connection { get; set; }
    }
}