using System.CodeDom.Compiler;
using System.Security.Cryptography.X509Certificates;

namespace EFAutomation
{
    public interface IAutoContextFactoryConfiguration
    {
        /// <summary>
        /// Gets or sets the directory to save all Code First migrations into
        /// </summary>
        string MigrationsDirectory { get; set; }
        /// <summary>
        /// Gets or sets a value indicating if automatic (non-code based) migrations should be used when migrating the database. Mutually exclusive with AutoGeneratedMigrationsEnabled.
        /// </summary>
        bool AutoMigrateToLatestVersionEnabled { get; set; }
        /// <summary>
        /// Gets or sets a value indicating if automatic (non-code based) migrations allow data loss. Only works with AutoMigrateToLatestVersionEnabled.
        /// </summary>
        bool AutomaticMigrationDataLossAllowed { get; set; }
        /// <summary>
        /// Gets or sets a value indicating if automatic (code based) migrations should be used when migrating the database. Mutually exclusive with AutoMigrateToLatestVersionEnabled.
        /// </summary>
        bool AutoGeneratedMigrationsEnabled { get; set; }
        /// <summary>
        /// Code provider to use for T4 generation. Only change if you know what you are doing.
        /// </summary>
        //CodeDomProvider CodeProvider { get; set; }


        /// <summary>
        /// Connection string or connection string name.
        /// </summary>
        string Connection { get; set; }
        /// <summary>
        /// Gets or sets a value indicating if automatic (code based) migrations should be automatically migrated when creating context. Only works with AutoGeneratedMigrationsEnabled.
        /// </summary>
        bool AutoMigrateGeneratedMigrationsEnabled { get; set; }
        /// <summary>
        /// Gets or sets a value indicating if automatic (code based) migrations should be compiled into (or loaded from) a file. Requires MigrationsAssemblyFileLocation to be set.
        /// </summary>
        bool MigrationsAssemblyAsFile { get; set; }
        /// <summary>
        /// Gets or sets a value indicating the location of compiled migrations assembly file. Only works with MigrationsAssemblyAsFile set to true.
        /// </summary>
        string MigrationsAssemblyFileLocation { get; set; }
    }
}